name: ANKI-HUB-iOS
options:
  bundleIdPrefix: com.ankihub
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"

targets:
  ANKI-HUB-iOS:
    type: application
    platform: iOS
    sources:
      - path: Sources/ANKI-HUB-iOS
        excludes:
          - "**/.DS_Store"
          - "Views/CalendarView.swift"
          - "Views/PomodoroView.swift"
          - "Views/ContentView.swift"
          - "Views/ManagementView.swift"
      - path: Sources/Shared
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ankihub.ios
        PRODUCT_NAME: sugwrAnki
        INFOPLIST_FILE: Sources/ANKI-HUB-iOS/Info.plist
        CODE_SIGN_ENTITLEMENTS: Sources/ANKI-HUB-iOS/ANKI-HUB-iOS.entitlements
        SYMROOT: "$(HOME)/Library/Developer/Xcode/DerivedData/ANKI-HUB-iOS-Build"
        OBJROOT: "$(HOME)/Library/Developer/Xcode/DerivedData/ANKI-HUB-iOS-Intermediates"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        MARKETING_VERSION: "2.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.9"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: K5D7GVJFG7
        CODE_SIGNING_ALLOWED[sdk=iphonesimulator*]: "NO"
        CODE_SIGNING_REQUIRED[sdk=iphonesimulator*]: "NO"
        CODE_SIGN_IDENTITY[sdk=iphonesimulator*]: ""
        SUPPORTS_MACCATALYST: false
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_EMIT_LOC_STRINGS: "YES"
        SWIFT_OPTIMIZATION_LEVEL: "-Onone"
      configs:
        Debug:
          DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG"
        Release:
          DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
          SWIFT_OPTIMIZATION_LEVEL: "-O"
    dependencies:
      - target: ANKI-HUB-iOS-Widget
        embed: true
    postBuildScripts: []

  ANKI-HUB-iOS-Widget:
    type: app-extension
    platform: iOS
    sources:
      - path: Sources/ANKI-HUB-iOS-Widget
        excludes:
          - "**/.DS_Store"
      - path: Sources/Shared
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ankihub.ios.widget
        PRODUCT_NAME: sugwrAnkiWidget
        INFOPLIST_FILE: Sources/ANKI-HUB-iOS-Widget/Info.plist
        CODE_SIGN_ENTITLEMENTS: Sources/ANKI-HUB-iOS-Widget/ANKI-HUB-iOS-Widget.entitlements
        SYMROOT: "$(HOME)/Library/Developer/Xcode/DerivedData/ANKI-HUB-iOS-Build"
        OBJROOT: "$(HOME)/Library/Developer/Xcode/DerivedData/ANKI-HUB-iOS-Intermediates"
        MARKETING_VERSION: "2.0.0"
        CURRENT_PROJECT_VERSION: "1"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        SWIFT_VERSION: "5.9"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: K5D7GVJFG7
        CODE_SIGNING_ALLOWED[sdk=iphonesimulator*]: "NO"
        CODE_SIGNING_REQUIRED[sdk=iphonesimulator*]: "NO"
        CODE_SIGN_IDENTITY[sdk=iphonesimulator*]: ""
    dependencies: []

schemes:
  ANKI-HUB-iOS:
    build:
      targets:
        ANKI-HUB-iOS: all
        ANKI-HUB-iOS-Widget: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  ANKI-HUB-iOS-Widget:
    build:
      targets:
        ANKI-HUB-iOS-Widget: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
